version: '3.1'

services:
  boiler-mongodb:
    container_name: boiler-mongodb
    image: mongo:4-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: boiler
      MONGO_INITDB_ROOT_PASSWORD: hello-boiler
    volumes:
      - ./.data/mongodb:/data/db
